# can specify one of the following keys: diameter [mm] (circular cross section), side_length [mm] (square cross section)
# or area [mm^2] (custom cross section)
diameter: 9.5 #mm

# three possible connection types: parallel-alternating, parallel and series
connection: parallel-alternating

# both optional, if not specified it will default to air
backing-material: Air
transmission-material: Air

frequency-band:
  min: 1 #MHz
  max: 50 #MHz

transducer: # thickness [um], counter-polarized means that the piezo crystal polarization direction is opposite to the current polarity
  - {material: "Au", thickness: 0.2}
  - {material: "P(VDF-TrFE)", thickness: 120, counter-polarized: True}
  - {material: "Au", thickness: 0.2}
  - {material: "Transfertape", thickness: 42} #43
  - {material: "Au", thickness: 0.2}
  - {material: "P(VDF-TrFE)", thickness: 120, counter-polarized: False}
  - {material: "Au", thickness: 0.2}